#!/usr/bin/env bash
# =============================================================================
#  Vulnerable Web Apps – Bare-Metal Installer (no Docker)
#  Installs alongside an existing nginx + DVWA setup.
#
#  Apps installed
#  ─────────────────────────────────────────────────────
#  PHP  (served via nginx at  http://<ip>/<app>)
#    • Mutillidae II        → /mutillidae
#    • bWAPP                → /bwapp
#    • WackoPicko           → /wackopicko
#    • Hackazon             → /hackazon
#
#  Standalone  (nginx reverse-proxied to a sub-path)
#    • OWASP WebGoat 2023   → /webgoat          (Java, port 8080)
#    • DVNA                 → /dvna             (Node, port 9090)
#    • OWASP Juice Shop     → /juice-shop       (Node, port 3000)
#    • WrongSecrets         → /wrongsecrets     (Java, port 8085)
#
#  Run as root on a Debian/Ubuntu host that already has nginx + PHP-FPM.
# =============================================================================

set -euo pipefail

### ── colour helpers ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERR]${NC}   $*"; exit 1; }

### ── sanity checks ───────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && error "Please run as root:  sudo bash install.sh"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEBROOT="/var/www/html"
LOG_FILE="/var/log/vuln-apps-install.log"

info "Logging to $LOG_FILE"
exec > >(tee -a "$LOG_FILE") 2>&1

### ── detect PHP version ─────────────────────────────────────────────────────
PHP_VER=$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;' 2>/dev/null || true)
[[ -z "$PHP_VER" ]] && error "PHP not found. Install php-fpm first (apt install php-fpm)."
PHP_FPM_SOCK="/run/php/php${PHP_VER}-fpm.sock"
info "Detected PHP $PHP_VER  (socket: $PHP_FPM_SOCK)"

### ── detect nginx config style ──────────────────────────────────────────────
NGINX_SITES="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"

### ── helper: write nginx location block ─────────────────────────────────────
write_nginx_location() {
    local APP_NAME="$1"   # e.g. mutillidae
    local TYPE="$2"       # php | proxy
    local PROXY_PORT="${3:-}"

    local CONF_FILE="${NGINX_SITES}/vuln-apps.conf"

    if [[ ! -f "$CONF_FILE" ]]; then
        cat > "$CONF_FILE" <<NGINXHDR
# Auto-generated by bare-installs/install.sh
# Add your server{} block reference here, or include from your main server block.
# The location blocks below are written for inclusion inside an existing server{} block.
# Run:  sudo cp ${NGINX_SITES}/vuln-apps.conf /etc/nginx/snippets/vuln-apps.conf
#       then add:  include snippets/vuln-apps.conf;  inside your main server {} block.

NGINXHDR
    fi

    if [[ "$TYPE" == "php" ]]; then
        cat >> "$CONF_FILE" <<PHPBLOCK

location /${APP_NAME} {
    alias ${WEBROOT}/${APP_NAME};
    index index.php index.html;
    try_files \$uri \$uri/ /${APP_NAME}/index.php\$is_args\$args;

    location ~ \.php$ {
        fastcgi_pass unix:${PHP_FPM_SOCK};
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \$request_filename;
    }
}
PHPBLOCK
    elif [[ "$TYPE" == "proxy" ]]; then
        cat >> "$CONF_FILE" <<PROXYBLOCK

location /${APP_NAME}/ {
    proxy_pass http://127.0.0.1:${PROXY_PORT}/${APP_NAME}/;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_read_timeout 300s;
}
PROXYBLOCK
    fi
}

### ── helper: enable + start a systemd unit ──────────────────────────────────
enable_service() {
    local NAME="$1"
    systemctl daemon-reload
    systemctl enable --now "$NAME"
    success "Service $NAME started"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 1 – System dependencies
# ═════════════════════════════════════════════════════════════════════════════
section_deps() {
    info "Installing system dependencies…"
    apt-get update -qq
    apt-get install -y --no-install-recommends \
        git curl wget unzip \
        "php${PHP_VER}" "php${PHP_VER}-fpm" \
        "php${PHP_VER}-mysql" "php${PHP_VER}-xml" "php${PHP_VER}-mbstring" \
        "php${PHP_VER}-curl" "php${PHP_VER}-gd" "php${PHP_VER}-ldap" \
        "php${PHP_VER}-zip" "php${PHP_VER}-bcmath" \
        mysql-server \
        openjdk-17-jre-headless \
        nodejs npm \
        python3 python3-pip

    # Make sure npm/node are reasonably new
    if node --version | grep -qE '^v1[0-5]\.'; then
        warn "Node.js is old; installing LTS via NodeSource…"
        curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
        apt-get install -y nodejs
    fi

    success "Dependencies ready"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 2 – MySQL: create databases & users
# ═════════════════════════════════════════════════════════════════════════════
section_mysql() {
    info "Configuring MySQL databases…"
    systemctl start mysql || true

    mysql -u root <<'SQL'
CREATE DATABASE IF NOT EXISTS mutillidae CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'mutillidae'@'localhost' IDENTIFIED BY 'mutillidae_pass';
GRANT ALL PRIVILEGES ON mutillidae.* TO 'mutillidae'@'localhost';

CREATE DATABASE IF NOT EXISTS bwapp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'bwapp'@'localhost' IDENTIFIED BY 'bwapp_pass';
GRANT ALL PRIVILEGES ON bwapp.* TO 'bwapp'@'localhost';

CREATE DATABASE IF NOT EXISTS hackazon CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'hackazon'@'localhost' IDENTIFIED BY 'hackazon_pass';
GRANT ALL PRIVILEGES ON hackazon.* TO 'hackazon'@'localhost';

FLUSH PRIVILEGES;
SQL
    success "MySQL databases created"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 3 – Mutillidae II  (PHP)
# ═════════════════════════════════════════════════════════════════════════════
install_mutillidae() {
    info "Installing Mutillidae II…"
    local DEST="${WEBROOT}/mutillidae"

    if [[ -d "$DEST" ]]; then
        warn "Mutillidae already present – skipping clone"
    else
        git clone --depth 1 \
            https://github.com/webpwnized/mutillidae.git \
            "$DEST"
    fi

    # Fix database config
    local CFG="${DEST}/classes/MySQLHandler.php"
    if [[ -f "$CFG" ]]; then
        sed -i "s/'DB_USERNAME', 'root'/'DB_USERNAME', 'mutillidae'/"    "$CFG" || true
        sed -i "s/'DB_PASSWORD', ''/'DB_PASSWORD', 'mutillidae_pass'/"   "$CFG" || true
        sed -i "s/'DB_NAME', 'mutillidae'/'DB_NAME', 'mutillidae'/"      "$CFG" || true
    fi

    chown -R www-data:www-data "$DEST"
    chmod -R 755 "$DEST"

    write_nginx_location "mutillidae" "php"
    success "Mutillidae II installed → http://<ip>/mutillidae"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 4 – bWAPP  (PHP)
# ═════════════════════════════════════════════════════════════════════════════
install_bwapp() {
    info "Installing bWAPP…"
    local DEST="${WEBROOT}/bwapp"

    if [[ -d "$DEST" ]]; then
        warn "bWAPP already present – skipping"
    else
        git clone --depth 1 \
            https://github.com/jehy-security/bWAPP-docker.git \
            /tmp/bwapp-src
        # the actual PHP lives inside bwapp/ subfolder of that repo
        cp -r /tmp/bwapp-src/bwapp "$DEST" 2>/dev/null || \
            cp -r /tmp/bwapp-src "$DEST"
        rm -rf /tmp/bwapp-src
    fi

    # Patch DB config
    local CFG="${DEST}/admin/settings.php"
    [[ -f "$CFG" ]] && {
        sed -i "s/\$db_username = .*/\$db_username = 'bwapp';/"          "$CFG"
        sed -i "s/\$db_password = .*/\$db_password = 'bwapp_pass';/"     "$CFG"
        sed -i "s/\$db_name = .*/\$db_name = 'bwapp';/"                  "$CFG"
    }

    chown -R www-data:www-data "$DEST"
    chmod -R 755 "$DEST"

    write_nginx_location "bwapp" "php"
    success "bWAPP installed → http://<ip>/bwapp  (run /bwapp/install.php to seed the DB)"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 5 – WackoPicko  (PHP)
# ═════════════════════════════════════════════════════════════════════════════
install_wackopicko() {
    info "Installing WackoPicko…"
    local DEST="${WEBROOT}/wackopicko"

    if [[ -d "$DEST" ]]; then
        warn "WackoPicko already present – skipping"
    else
        git clone --depth 1 \
            https://github.com/adamdoupe/WackoPicko.git \
            "$DEST"
    fi

    # WackoPicko uses its own config
    local CFG="${DEST}/WackoPicko/includes/database.php"
    [[ -f "$CFG" ]] && {
        sed -i "s/db_user   = .*/db_user   = 'root';/"   "$CFG" || true
    }

    chown -R www-data:www-data "$DEST"
    chmod -R 755 "$DEST"

    write_nginx_location "wackopicko" "php"
    success "WackoPicko installed → http://<ip>/wackopicko"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 6 – Hackazon  (PHP)
# ═════════════════════════════════════════════════════════════════════════════
install_hackazon() {
    info "Installing Hackazon…"
    local DEST="${WEBROOT}/hackazon"

    if [[ -d "$DEST" ]]; then
        warn "Hackazon already present – skipping"
    else
        git clone --depth 1 \
            https://github.com/rapid7/hackazon.git \
            "$DEST"
    fi

    # Composer install if available
    if command -v composer &>/dev/null; then
        (cd "$DEST" && composer install --no-interaction --no-dev 2>/dev/null) || true
    else
        warn "Composer not found – Hackazon may need manual 'composer install'"
    fi

    local CFG="${DEST}/config/db.php"
    if [[ ! -f "$CFG" && -f "${DEST}/config/db.php.example" ]]; then
        cp "${DEST}/config/db.php.example" "$CFG"
    fi
    [[ -f "$CFG" ]] && {
        sed -i "s/'username' *=> *'.*'/'username' => 'hackazon'/"    "$CFG" || true
        sed -i "s/'password' *=> *'.*'/'password' => 'hackazon_pass'/" "$CFG" || true
        sed -i "s/'dbname'   *=> *'.*'/'dbname'   => 'hackazon'/"    "$CFG" || true
    }

    chown -R www-data:www-data "$DEST"
    chmod -R 755 "$DEST"

    write_nginx_location "hackazon" "php"
    success "Hackazon installed → http://<ip>/hackazon"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 7 – OWASP WebGoat 2023  (Java – standalone JAR on port 8080)
# ═════════════════════════════════════════════════════════════════════════════
install_webgoat() {
    info "Installing OWASP WebGoat…"
    local INSTALL_DIR="/opt/webgoat"
    local JAR_URL="https://github.com/WebGoat/WebGoat/releases/download/v2023.8/webgoat-2023.8.jar"
    local JAR="${INSTALL_DIR}/webgoat.jar"

    mkdir -p "$INSTALL_DIR"

    if [[ -f "$JAR" ]]; then
        warn "WebGoat JAR already present – skipping download"
    else
        info "Downloading WebGoat JAR (~130 MB)…"
        wget -q --show-progress -O "$JAR" "$JAR_URL"
    fi

    # Create dedicated user
    id -u webgoat &>/dev/null || useradd -r -s /bin/false -d "$INSTALL_DIR" webgoat
    chown -R webgoat:webgoat "$INSTALL_DIR"

    # Systemd service
    cat > /etc/systemd/system/webgoat.service <<UNIT
[Unit]
Description=OWASP WebGoat
After=network.target

[Service]
User=webgoat
WorkingDirectory=${INSTALL_DIR}
ExecStart=/usr/bin/java -Dfile.encoding=UTF-8 \
    --add-opens java.base/java.lang=ALL-UNNAMED \
    --add-opens java.base/java.util=ALL-UNNAMED \
    -jar ${JAR} \
    --server.port=8080 \
    --server.address=127.0.0.1 \
    --webgoat.host=127.0.0.1 \
    --webgoat.port=8080 \
    --webwolf.host=127.0.0.1 \
    --webwolf.port=9090
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

    enable_service webgoat

    # NOTE: WebGoat serves at /WebGoat, not /webgoat
    cat >> "${NGINX_SITES}/vuln-apps.conf" <<'WGBLOCK'

# WebGoat – reverse proxy (runs on port 8080)
location /WebGoat {
    proxy_pass http://127.0.0.1:8080/WebGoat;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_read_timeout 300s;
}
WGBLOCK

    success "WebGoat installed → http://<ip>/WebGoat  (may take ~60 s to start)"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 8 – DVNA – Damn Vulnerable Node.js App  (Node – port 9001)
# ═════════════════════════════════════════════════════════════════════════════
install_dvna() {
    info "Installing DVNA…"
    local INSTALL_DIR="/opt/dvna"

    if [[ -d "$INSTALL_DIR" ]]; then
        warn "DVNA directory already exists – skipping clone"
    else
        git clone --depth 1 \
            https://github.com/appsecco/dvna.git \
            "$INSTALL_DIR"
    fi

    (cd "$INSTALL_DIR" && npm install --omit=dev 2>/dev/null)

    # Create .env
    cat > "${INSTALL_DIR}/.env" <<ENV
MYSQL_USER=root
MYSQL_DATABASE=dvna
MYSQL_PASSWORD=
MYSQL_HOST=127.0.0.1
MYSQL_PORT=3306
PORT=9001
ENV

    mysql -u root -e "CREATE DATABASE IF NOT EXISTS dvna;" || true

    id -u dvna &>/dev/null || useradd -r -s /bin/false -d "$INSTALL_DIR" dvna
    chown -R dvna:dvna "$INSTALL_DIR"

    cat > /etc/systemd/system/dvna.service <<UNIT
[Unit]
Description=DVNA – Damn Vulnerable Node.js App
After=network.target mysql.service

[Service]
User=dvna
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${INSTALL_DIR}/.env
ExecStart=$(which node) server.js
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

    enable_service dvna
    write_nginx_location "dvna" "proxy" "9001"
    success "DVNA installed → http://<ip>/dvna"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 9 – OWASP Juice Shop  (Node – port 3000)
# ═════════════════════════════════════════════════════════════════════════════
install_juiceshop() {
    info "Installing OWASP Juice Shop…"
    local INSTALL_DIR="/opt/juice-shop"
    local JS_VER="v17.0.0"
    local TARBALL="juice-shop-${JS_VER}_node20_linux_x64.tgz"
    local DL_URL="https://github.com/juice-shop/juice-shop/releases/download/${JS_VER}/${TARBALL}"

    mkdir -p "$INSTALL_DIR"

    if [[ -f "${INSTALL_DIR}/package.json" ]]; then
        warn "Juice Shop already present – skipping download"
    else
        info "Downloading Juice Shop pre-built package (~250 MB)…"
        wget -q --show-progress -O "/tmp/${TARBALL}" "$DL_URL"
        tar -xzf "/tmp/${TARBALL}" -C "$INSTALL_DIR" --strip-components=1
        rm -f "/tmp/${TARBALL}"
    fi

    id -u juiceshop &>/dev/null || useradd -r -s /bin/false -d "$INSTALL_DIR" juiceshop
    chown -R juiceshop:juiceshop "$INSTALL_DIR"

    cat > /etc/systemd/system/juiceshop.service <<UNIT
[Unit]
Description=OWASP Juice Shop
After=network.target

[Service]
User=juiceshop
WorkingDirectory=${INSTALL_DIR}
Environment=PORT=3000
ExecStart=$(which node) app.js
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

    enable_service juiceshop

    # Juice Shop runs at root /, so we expose it on a dedicated path via nginx
    cat >> "${NGINX_SITES}/vuln-apps.conf" <<'JSBLOCK'

# OWASP Juice Shop – runs at root, so we proxy the whole path prefix
location /juice-shop/ {
    proxy_pass http://127.0.0.1:3000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_read_timeout 120s;
}
JSBLOCK

    success "Juice Shop installed → http://<ip>/juice-shop/"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 10 – WrongSecrets  (Java – port 8085)
# ═════════════════════════════════════════════════════════════════════════════
install_wrongsecrets() {
    info "Installing OWASP WrongSecrets…"
    local INSTALL_DIR="/opt/wrongsecrets"
    local JAR_URL="https://github.com/OWASP/wrongsecrets/releases/download/v1.12.0/wrongsecrets-1.12.0.jar"
    local JAR="${INSTALL_DIR}/wrongsecrets.jar"

    mkdir -p "$INSTALL_DIR"

    if [[ -f "$JAR" ]]; then
        warn "WrongSecrets JAR already present – skipping"
    else
        info "Downloading WrongSecrets JAR (~80 MB)…"
        wget -q --show-progress -O "$JAR" "$JAR_URL"
    fi

    id -u wrongsecrets &>/dev/null || useradd -r -s /bin/false -d "$INSTALL_DIR" wrongsecrets
    chown -R wrongsecrets:wrongsecrets "$INSTALL_DIR"

    cat > /etc/systemd/system/wrongsecrets.service <<UNIT
[Unit]
Description=OWASP WrongSecrets
After=network.target

[Service]
User=wrongsecrets
WorkingDirectory=${INSTALL_DIR}
ExecStart=/usr/bin/java -jar ${JAR} --server.port=8085 --server.address=127.0.0.1
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

    enable_service wrongsecrets
    write_nginx_location "wrongsecrets" "proxy" "8085"
    success "WrongSecrets installed → http://<ip>/wrongsecrets"
}

# ═════════════════════════════════════════════════════════════════════════════
#  SECTION 11 – Finalize nginx config
# ═════════════════════════════════════════════════════════════════════════════
finalize_nginx() {
    info "Finalising nginx configuration…"

    local SNIPPET_DIR="/etc/nginx/snippets"
    mkdir -p "$SNIPPET_DIR"
    cp "${NGINX_SITES}/vuln-apps.conf" "${SNIPPET_DIR}/vuln-apps.conf"

    # Try to detect the main server block file (assume it's the default site)
    local MAIN_CONF
    for F in \
        /etc/nginx/sites-enabled/default \
        /etc/nginx/sites-available/default \
        /etc/nginx/conf.d/default.conf; do
        [[ -f "$F" ]] && { MAIN_CONF="$F"; break; }
    done

    if [[ -n "${MAIN_CONF:-}" ]]; then
        if grep -q "vuln-apps.conf" "$MAIN_CONF"; then
            warn "nginx already includes vuln-apps snippet – skipping"
        else
            # Insert include just before the closing brace of the first server block
            sed -i '/^}/i\    include snippets\/vuln-apps.conf;' "$MAIN_CONF"
            success "Inserted snippet include into $MAIN_CONF"
        fi
    else
        warn "Could not auto-detect main nginx server block."
        warn "Please add the following line inside your server {} block manually:"
        warn "    include snippets/vuln-apps.conf;"
    fi

    nginx -t && systemctl reload nginx && success "nginx reloaded"
}

# ═════════════════════════════════════════════════════════════════════════════
#  MAIN
# ═════════════════════════════════════════════════════════════════════════════
main() {
    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║   Vulnerable Apps – Bare-Metal Installer          ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════════╝${NC}"
    echo ""

    # Remove old snippet so we start fresh on each run
    rm -f "${NGINX_SITES}/vuln-apps.conf"

    section_deps
    section_mysql

    install_mutillidae
    install_bwapp
    install_wackopicko
    install_hackazon

    install_webgoat
    install_dvna
    install_juiceshop
    install_wrongsecrets

    finalize_nginx

    echo ""
    echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Installation complete!  Summary:${NC}"
    echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
    local IP
    IP=$(hostname -I | awk '{print $1}')
    echo ""
    echo -e "  ${CYAN}PHP apps (served directly by nginx)${NC}"
    echo -e "  ● Mutillidae II   →  http://${IP}/mutillidae"
    echo -e "  ● bWAPP           →  http://${IP}/bwapp  (visit /bwapp/install.php first)"
    echo -e "  ● WackoPicko      →  http://${IP}/wackopicko"
    echo -e "  ● Hackazon        →  http://${IP}/hackazon"
    echo ""
    echo -e "  ${CYAN}Standalone apps (reverse-proxied through nginx)${NC}"
    echo -e "  ● WebGoat 2023    →  http://${IP}/WebGoat   (Java, ~60 s startup)"
    echo -e "  ● DVNA            →  http://${IP}/dvna"
    echo -e "  ● Juice Shop      →  http://${IP}/juice-shop/"
    echo -e "  ● WrongSecrets    →  http://${IP}/wrongsecrets"
    echo ""
    echo -e "  ${YELLOW}Your existing DVWA should still be at http://${IP}/DVWA${NC}"
    echo ""
    echo -e "  Full log: ${LOG_FILE}"
    echo ""
}

main "$@"
